// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/piresc/product-app/internal/entity"
	"github.com/piresc/product-app/internal/handler/http"
)

// Injectors from wire.go:

// InitializeApp initializes the application with all dependencies
func InitializeApp(cfg *entity.Config) *http.RestApp {
	productRepo := provideProductRepo(cfg)
	productUsecase := provideProductUsecase(productRepo)
	restApp := provideProductApp(productUsecase)
	return restApp
}
